services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn my_new_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9